### ISSUE TITLE
React Diff算法解析

### ISSUE THREAD

**Issue by campcc** [campcc/blog#13]
<img src="https://www.cronj.com/blog/wp-content/uploads/Diff-2.png" />

React 高效性能的背后得益于 **Virtual DOM** 和 **Diff 算法**，而 Diff 算法要解决的根本问题就是：Virtual DOM 变化时，计算差异部分用于局部更新，而虚拟DOM本质上就是一个树形对象，所以问题转化两棵树的对比。

对比两棵树的差异本就是一个复杂的问题，如果使用传统的 Diff 算法，通过循环递归对树节点依次进行对比，不仅效率低下，算法的时间复杂度更是达到 O(n^3)，其中 n 是树节点的总数。O(n^3) 意味着如果要展示 1000 个节点，需要进行上十亿次的比较，这种指数型的性能消耗对于前端渲染场景来说代价太高了，现今的 CPU 每秒钟能执行大约 30 亿条指令，即便是最高效的实现，也不可能在一秒内计算出差异情况。

所以，如果想要将 Diff 思想引入 Virtual DOM，就需要降低 Diff 算法的时间复杂度。

React 开发团队针对前端渲染场景和 React 组件化的思想，制定了三个大胆的策略，将时间复杂度从 O(n^3) 降到 O(n)。

## Diff策略

在保证页面整体构建性能的前提下，React 团队提出了三个 Diff 策略：

1. Web UI 中 DOM 节点跨层级的移动操作特别少，可以忽略不计
2. 拥有相同类的两个组件会生成相似的树形结构，拥有不同类的两个组件将会生成不同的树形结构
3. 同一层级的子节点可以通过唯一的 id 进行区分

## Diff粒度

基于上诉的三个 Diff 策略，将Diff算法的执行分为三个维度：**Tree Diff**、**Component Diff**，**Element Diff**。

三个 Diff 的差异在于：粒度不同和执行的顺序不同，执行顺序依次为：Tree Diff, Component Diff, Element Diff。

### Tree Diff

由于 DOM 节点跨层级的操作特别少，所以 React 对树的遍历算法进行了优化，通过层级控制进行分层比较，这样只需要一次遍历，就能完成整个 DOM 树的比较。

```js
updateChildren: function(nextNestedChildrenElements, transaction, context) {
  updateDepth++;
  var errorThrown = true;
  try {
    this._updateChildren(nextNestedChildrenElements, transaction, context);
    errorThrown = false;
  } finally {
    updateDepth--;
    if (!updateDepth) {
      if (errorThrown) {
        clearQueue();
      } else {
        processQueue();
      }
    }
  }
}
```

具体来说，Tree Diff 会对树的每一层进行遍历，如果发现某个节点不存在了，会直接销毁，其对应的子节点也会完全被删除掉：

<img src="https://pic2.zhimg.com/d712a73769688afe1ef1a055391d99ed_r.jpg" />

以上图为例，由于 React 只会简单的考虑同层级节点的位置变换，而对于不同层级的节点，只有创建和删除操作。当根节点发现子节点中 A 消失了，就会直接销毁 A；当 D 发现多了一个子节点 A，则会创建新的 A（包括子节点）作为其子节点。此时，React diff 的执行情况：**create A -> create B -> create C -> delete A**。

同时我们也注意到，当出现 **节点跨层级移动** 时，React 不会进行移动操作，而是以 A 为根节点的整个树被重新创建，所以这是影响 React 性能的操作，因此 [React 官方建议不要进行 DOM 节点跨层级的操作](https://reactjs.org/docs/reconciliation.html#the-diffing-algorithm)。

所以在开发组件时，保持一个稳定的 DOM 结构会有助于性能的提升。例如使用 CSS 隐藏或显示节点，而不是真的移除或添加 DOM 节点。

### Component Diff

React 基于组件构建用户界面，组件在 Virtual DOM 中体现为一个节点。

对于组件的比较，基于策略二，React 团队采取的方法是：

- 对于同一类型的组件，按照原策略继续比较
- 对于不同类型的组件，直接进行替换

我们先说对于同类型的组件（即拥有相同类的组件），有可能 Virtual DOM 没有任何变化，这个时候其实不需要进行比较，所以 React 允许用户通过 **shouldComponentUpdate** 方法来判断该组件是否需要进行 Diff，[这也是常见的一种优化手段](https://reactjs.org/docs/optimizing-performance.html#shouldcomponentupdate-in-action)。

对于不同类型的组件，即使它们的结构相似，React 也不会进行比较，而是直接进行替换，以下图为例：

<img src="https://pic1.zhimg.com/52654992aba15fc90e2dac8b2387d0c4_r.jpg" />

进行 Component Diff 时，React 发现组件 D 和 G 是不同类型的组件，React 会直接删除组件 D 及其子节点，然后重新创建组件 G 及其子节点。此时 Diff 顺序为：**delete E -> delete F -> delete D -> create E -> create F -> create G**。

你是否有疑问，组件 D 和 G 的结构相似，都有相同的子节点 E 和 F，直接将 D 和 G 进行替换不就行了吗，为什么要删除相同的子节点然后又创建呢？是的，当两个组件是不同类型但结构相似时，React diff 确实会影响性能，但是正如 React 官方博客所言：不同类型的组件是很少存在相似 DOM tree 的机会的，因此这种极端因素很难在实际开发过程中造成重大影响。

### Element Diff

我们刚才说，对于同一类型的组件，会继续比较下去，所以 Element Diff 其实就是对于同一层级的兄弟节点的策略。

当节点处于同一层级时，React 提供了三种对于节点的操作：

- **INSERT_MARKUP**（插入），当节点是全新的节点时，执行插入操作。
- **MOVE_EXISTING**（移动），节点存在于旧的 Virtual DOM tree，且可复用时，执行移动操作。
- **REMOVE_NODE**（删除），新的 Virtual DOM tree 不存在该节点，或者虽然存在但是不可复用（对应的 element 不同）时，执行删除操作。

```js
function enqueueInsertMarkup(parentInst, markup, toIndex) {
  updateQueue.push({
    parentInst: parentInst,
    parentNode: null,
    type: ReactMultiChildUpdateTypes.INSERT_MARKUP,
    markupIndex: markupQueue.push(markup) - 1,
    content: null,
    fromIndex: null,
    toIndex: toIndex,
  });
}

function enqueueMove(parentInst, fromIndex, toIndex) {
  updateQueue.push({
    parentInst: parentInst,
    parentNode: null,
    type: ReactMultiChildUpdateTypes.MOVE_EXISTING,
    markupIndex: null,
    content: null,
    fromIndex: fromIndex,
    toIndex: toIndex,
  });
}

function enqueueRemove(parentInst, fromIndex) {
  updateQueue.push({
    parentInst: parentInst,
    parentNode: null,
    type: ReactMultiChildUpdateTypes.REMOVE_NODE,
    markupIndex: null,
    content: null,
    fromIndex: fromIndex,
    toIndex: null,
  });
}
```

对于同一层级的节点，如下图所示：

<img src="https://pic2.zhimg.com/80/7541670c089b84c59b84e9438e92a8e9_hd.png" />

老集合中包含节点：A，B，C，D，更新后新集合中包含节点：B，A，D，C，此时新老集合进行 diff 差异化对比，发现 B != A，则创建并插入 B 至新集合，删除老集合 A，以此类推，创建并插入 A、D 和 C，删除 B、C 和 D。

但是 React 团队发现这类操作繁琐冗余，因为这些都是相同的节点，但由于位置发生变化，导致需要进行繁杂低效的删除、创建操作，其实只要对这些节点进行位置移动即可。

针对这一现象，React 提出优化策略：允许开发者对同一层级的同组子节点，添加唯一 key 进行区分，虽然只是小小的改动，性能上却发生了翻天覆地的变化：

<img src="https://pic1.zhimg.com/80/7b9beae0cf0a5bc8c2e82d00c43d1c90_hd.png" />

React 首先会收集新老集合中的 key，然后对新集合的节点进行遍历，通过唯一的 key 就可以判断新老集合中是否存在相同的节点，如果存在相同节点，则进行移动操作；如果新集合中有新加入的节点，会创建新节点；最后对老集合进行循环遍历，判断是否存在新集合中没有但老集合中仍存在的节点，如果发现这样的节点，删除。

```js
_updateChildren: function(nextNestedChildrenElements, transaction, context) {
  var prevChildren = this._renderedChildren;
  var nextChildren = this._reconcilerUpdateChildren(
    prevChildren, nextNestedChildrenElements, transaction, context
  );
  if (!nextChildren && !prevChildren) {
    return;
  }
  var name;
  var lastIndex = 0;
  var nextIndex = 0;
  for (name in nextChildren) {
    if (!nextChildren.hasOwnProperty(name)) {
      continue;
    }
    var prevChild = prevChildren && prevChildren[name];
    var nextChild = nextChildren[name];
    if (prevChild === nextChild) {
      this.moveChild(prevChild, nextIndex, lastIndex);
      lastIndex = Math.max(prevChild._mountIndex, lastIndex);
      prevChild._mountIndex = nextIndex;
    } else {
      if (prevChild) {
        lastIndex = Math.max(prevChild._mountIndex, lastIndex);
        this._unmountChild(prevChild);
      }
      this._mountChildAtIndex(
        nextChild, nextIndex, transaction, context
      );
    }
    nextIndex++;
  }
  for (name in prevChildren) {
    if (prevChildren.hasOwnProperty(name) &&
        !(nextChildren && nextChildren.hasOwnProperty(name))) {
      this._unmountChild(prevChildren[name]);
    }
  }
  this._renderedChildren = nextChildren;
},

moveChild: function(child, toIndex, lastIndex) {
  if (child._mountIndex < lastIndex) {
    this.prepareToManageChildren();
    enqueueMove(this, child._mountIndex, toIndex);
  }
},

createChild: function(child, mountImage) {
  this.prepareToManageChildren();
  enqueueInsertMarkup(this, mountImage, child._mountIndex);
},

removeChild: function(child) {
  this.prepareToManageChildren();
  enqueueRemove(this, child._mountIndex);
},

_unmountChild: function(child) {
  this.removeChild(child);
  child._mountIndex = null;
},

_mountChildAtIndex: function(
  child,
  index,
  transaction,
  context) {
  var mountImage = ReactReconciler.mountComponent(
    child,
    transaction,
    this,
    this._nativeContainerInfo,
    context
  );
  child._mountIndex = index;
  this.createChild(child, mountImage);
},
```

行文至此，你应该知道为什么 **React 建议在列表组件中使用唯一的 key，而且不建议使用数组下标作为 key**。

tips：使用数组下标作为 key 的弊端可以看这篇文章，[Index as a key is an anti-pattern](https://medium.com/@robinpokorny/index-as-a-key-is-an-anti-pattern-e0349aece318)。

## 参考链接

- [React Docs](https://reactjs.org/)
- [React 源码剖析系列 － 不可思议的 react diff](https://zhuanlan.zhihu.com/p/20346379)
- [云栖社区-图解React Diff算法](https://yq.aliyun.com/video/play/1427?spm=a2c4e.11153940.0.0.7aa254a6V69GDh)

(完)

**Comment by MrWangJustToDo** [comment]
强势围观
